name: Build LightningCSS Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android ARM64
    runs-on: ubuntu-latest

    env:
      TARGET: aarch64-linux-android
      NAPI_CLI_VERSION: latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install tools
        run: sudo apt update && sudo apt install -y build-essential pkg-config cmake ninja-build python3 unzip

      - name: Install napi-cli
        run: cargo install --locked napi-cli

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Set linker for Android
        run: |
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV
          echo "CC_aarch64_linux_android=${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV

      - name: Build lightningcss for Android
        run: |
          cd crates/node
          napi build --platform --target $TARGET --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lightningcss-android.node
          path: crates/node/npm/android-arm64-gnu/index.node
